/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BlueCarbonRegistry } from './BlueCarbonRegistry.js';
export * as factories from './factories/index.js';
export { BlueCarbonRegistry__factory } from './factories/BlueCarbonRegistry__factory.js';