"use client";

import React, { useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { motion } from "framer-motion";
import {
  ArrowLeft,
  Building2,
  MapPin,
  Maximize2,
  Calendar,
  ShieldCheck,
  FileCheck2,
  Activity,
  Layers,
  Sparkles,
  Download,
  BarChart3,
  CheckCircle2,
  Satellite,
  Trees,
  Eye,
  Check,
  Clock,
  Coins,
  Lock,
  ArrowRight,
  Info,
  Store,
} from "lucide-react";

import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { getSupabaseClient } from "@/lib/supabase";

const AIML_API_URL = "/api/aiml";

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.08,
      delayChildren: 0.05,
    },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 16 },
  visible: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.45,
      ease: [0.16, 1, 0.3, 1],
    },
  },
};

export default function ProjectDetailsPage() {
  const router = useRouter();
  const params = useParams();

  const projectId = String(params.projectId);

  const [activeTab, setActiveTab] = useState<
    "overview" | "baseline" | "mrv" | "credits"
  >("overview");

  const [selectedFile, setSelectedFile] = useState<File | null>(null);

  const [isAnalyzing, setIsAnalyzing] = useState(false);

  const [analysisMessage, setAnalysisMessage] = useState("");

  const [analysisResult, setAnalysisResult] =
    useState<any>(null);

  const [analysisDate, setAnalysisDate] =
    useState<string | null>(null);

  /*
   * ============================================================
   * TABS
   * ============================================================
   */

  const tabs = [
    {
      id: "overview",
      label: "Overview",
    },
    {
      id: "baseline",
      label: "AI Baseline",
    },
    {
      id: "mrv",
      label: "MRV & Verification",
    },
    {
      id: "credits",
      label: "Carbon Credits",
    },
  ];

  /*
   * ============================================================
   * UPLOAD BASELINE REPORT TO SUPABASE STORAGE
   * ============================================================
   *
   * FastAPI-generated Excel
   *        ↓
   * /api/aiml/report
   *        ↓
   * Supabase Storage
   *        ↓
   * baseline_reports.report_file_url
   */

  const handleBaselineStorageSync = async (
    farmerProjectId: string,
    farmerId: string,
    supabase: any
  ) => {
    // Fetch the Excel report generated by the FastAPI backend.
    const reportRes = await fetch(`${AIML_API_URL}/report`, {
      cache: "no-store",
    });

    if (!reportRes.ok) {
      const responseText = await reportRes.text().catch(() => "");
      console.error("Failed to fetch generated Excel report:", {
        status: reportRes.status,
        statusText: reportRes.statusText,
        responseText,
      });
      throw new Error(
        `Failed to fetch generated Excel report (HTTP ${reportRes.status}).`
      );
    }

    const reportBlob = await reportRes.blob();

    if (reportBlob.size === 0) {
      throw new Error("The generated Excel report is empty.");
    }

    const reportStoragePath =
      `${farmerProjectId}/BlueCarbon_Baseline_Report.xlsx`;

    console.log("Uploading baseline report to Supabase Storage:", {
      bucket: "baseline-reports",
      path: reportStoragePath,
      sizeBytes: reportBlob.size,
      farmerProjectId,
      farmerId,
    });

    // Upload (or replace) the report in the existing Storage bucket.
    const { error: uploadError } = await supabase.storage
      .from("baseline-reports")
      .upload(reportStoragePath, reportBlob, {
        upsert: true,
        contentType:
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      });

    if (uploadError) {
      console.error(
        "Baseline report Storage upload error:",
        JSON.stringify(uploadError, null, 2)
      );
      throw new Error(
        `Storage upload failed: ${uploadError.message}`
      );
    }

    // Generate the public URL for the uploaded report.
    const { data: publicUrlData } = supabase.storage
      .from("baseline-reports")
      .getPublicUrl(reportStoragePath);

    const reportFileUrl = publicUrlData?.publicUrl;

    if (!reportFileUrl) {
      throw new Error(
        "The report was uploaded, but Supabase did not return a Storage URL."
      );
    }

    console.log("Generated baseline report URL:", reportFileUrl);

    // Update the exact farmer/project row and return it so a zero-row
    // update cannot silently appear successful.
    const {
      data: updatedReport,
      error: dbError,
    } = await supabase
      .from("baseline_reports")
      .update({
        report_file_url: reportFileUrl,
      })
      .eq("project_id", farmerProjectId)
      .eq("farmer_id", farmerId)
      .select("id, project_id, farmer_id, report_file_url")
      .maybeSingle();

    if (dbError) {
      console.error(
        "Failed to save report_file_url in baseline_reports:",
        JSON.stringify(dbError, null, 2)
      );
      throw new Error(
        `Failed to save report URL to baseline_reports: ${dbError.message}`
      );
    }

    if (!updatedReport) {
      console.error(
        "No baseline_reports row was updated. Check row existence and Supabase RLS policies.",
        {
          project_id: farmerProjectId,
          farmer_id: farmerId,
          report_file_url: reportFileUrl,
        }
      );
      throw new Error(
        "The Excel file was uploaded, but no matching baseline_reports row was updated. Check that project_id and farmer_id match the saved report and that Supabase UPDATE/SELECT policies allow this farmer."
      );
    }

    if (!updatedReport.report_file_url) {
      throw new Error(
        "Supabase returned the updated report row, but report_file_url is still empty."
      );
    }

    console.log("Baseline report URL saved successfully:", {
      id: updatedReport.id,
      project_id: updatedReport.project_id,
      farmer_id: updatedReport.farmer_id,
      report_file_url: updatedReport.report_file_url,
    });

    return updatedReport.report_file_url as string;
  };

  /*
   * ============================================================
   * GENERATE BASELINE
   * ============================================================
   *
   * ZIP upload
   *     ↓
   * Python YOLO API
   *     ↓
   * Aggregated baseline result
   *     ↓
   * Save baseline_reports
   *     ↓
   * Upload Excel to Supabase Storage
   *     ↓
   * Save report_file_url
   *     ↓
   * Create/update mangrove_projects
   *     ↓
   * status = PENDING_VERIFICATION
   *     ↓
   * Authority Review
   *     ↓
   * status = APPROVED
   *     ↓
   * Industry Marketplace can display it
   *
   * Authority approval is required for marketplace visibility.
   */

  const analyzeBaseline = async () => {
    if (!selectedFile) {
      setAnalysisMessage(
        "Please select a ZIP file first."
      );
      return;
    }

    setIsAnalyzing(true);
    setAnalysisMessage("");
    setAnalysisResult(null);
    setAnalysisDate(null);

    try {
      /*
       * --------------------------------------------------------
       * SEND ZIP TO PYTHON AIML API
       * --------------------------------------------------------
       */

      const formData = new FormData();

      formData.append(
        "file",
        selectedFile
      );

      const response = await fetch(
        `${AIML_API_URL}/baseline`,
        {
          method: "POST",
          body: formData,
        }
      );

      const result =
        await response.json();

      if (
        !response.ok ||
        !result.success
      ) {
        throw new Error(
          result.error ||
            "Baseline analysis failed."
        );
      }

      /*
       * --------------------------------------------------------
       * STORE REAL AI RESULT IN UI
       * --------------------------------------------------------
       */

      setAnalysisResult(result);

      const completedAt =
        new Date().toISOString();

      setAnalysisDate(
        completedAt
      );

      /*
       * --------------------------------------------------------
       * EXTRACT REAL AI VALUES
       * --------------------------------------------------------
       */

      const imagesProcessed =
        Number(
          result.images_processed ||
            0
        );

      const totalDetections =
        Number(
          result.total_detections ||
            0
        );

      const areaHa =
        Number(
          result.total_area_hectares ??
            result.area_ha ??
            0
        );

      const totalCo2e =
        Number(
          result.total_co2e ??
            result.total_co2_tons ??
            0
        );

      /*
       * --------------------------------------------------------
       * SUPABASE
       * --------------------------------------------------------
       */

      const supabase =
        getSupabaseClient();

      if (!supabase) {
        throw new Error(
          "Supabase client is not available."
        );
      }

      /*
       * --------------------------------------------------------
       * GET CURRENT FARMER
       * --------------------------------------------------------
       */

      const {
        data: sessionData,
      } =
        await supabase.auth.getSession();

      const farmerId =
        sessionData.session?.user?.id ??
        null;

      if (!farmerId) {
        throw new Error(
          "Farmer session not found. Please login again."
        );
      }

      /*
       * ========================================================
       * CREATE A FARMER-SPECIFIC PROJECT ID
       * ========================================================
       */

      let farmerProjectId =
        `${projectId}-${farmerId.slice(
          0,
          8
        )}`;

      /*
       * Check whether this Farmer already owns the original
       * project ID.
       */

      const {
        data: existingOwnedProject,
        error: existingProjectError,
      } = await supabase
        .from("mangrove_projects")
        .select("project_id")
        .eq(
          "project_id",
          String(projectId)
        )
        .eq(
          "farmer_id",
          farmerId
        )
        .maybeSingle();

      if (existingProjectError) {
        console.error(
          "Existing project lookup error:",
          JSON.stringify(
            existingProjectError,
            null,
            2
          )
        );

        throw new Error(
          "Could not check your existing project."
        );
      }

      if (existingOwnedProject) {
        farmerProjectId =
          existingOwnedProject.project_id;
      }

      console.log(
        "Farmer ID:",
        farmerId
      );

      console.log(
        "Farmer Project ID:",
        farmerProjectId
      );

      /*
       * ========================================================
       * SAVE / UPDATE BASELINE REPORT
       * ========================================================
       */

      const {
        data: existingReport,
        error: existingReportError,
      } = await supabase
        .from("baseline_reports")
        .select("id")
        .eq(
          "project_id",
          farmerProjectId
        )
        .eq(
          "farmer_id",
          farmerId
        )
        .maybeSingle();

      if (existingReportError) {
        console.error(
          "Existing baseline report lookup error:",
          JSON.stringify(
            existingReportError,
            null,
            2
          )
        );

        throw new Error(
          "Could not check the existing baseline report."
        );
      }

      const reportPayload = {
        project_id:
          farmerProjectId,

        farmer_id:
          farmerId,

        status:
          "completed",

        images_processed:
          imagesProcessed,

        total_detections:
          totalDetections,

        total_area_m2:
          Number(
            result.total_area_m2 ||
              0
          ),

        area_ha:
          areaHa,

        agb_tC:
          Number(
            result.total_agb_tC ??
              result.agb_tC ??
              0
          ),

        bgb_tC:
          Number(
            result.total_bgb_tC ??
              result.bgb_tC ??
              0
          ),

        soc_tC:
          Number(
            result.total_soc_tC ??
              result.soc_tC ??
              0
          ),

        total_carbon_tC:
          Number(
            result.total_carbon_tC ??
              result.total_carbon ??
              0
          ),

        total_co2e:
          totalCo2e,
      };

      if (existingReport) {
        const {
          error: reportUpdateError,
        } = await supabase
          .from("baseline_reports")
          .update(
            reportPayload
          )
          .eq(
            "id",
            existingReport.id
          );

        if (reportUpdateError) {
          console.error(
            "Baseline report update error:",
            JSON.stringify(
              reportUpdateError,
              null,
              2
            )
          );

          throw new Error(
            "Baseline report could not be updated."
          );
        }
      } else {
        const {
          error: reportInsertError,
        } = await supabase
          .from("baseline_reports")
          .insert(
            reportPayload
          );

        if (reportInsertError) {
          console.error(
            "Baseline report insert error:",
            JSON.stringify(
              reportInsertError,
              null,
              2
            )
          );

          throw new Error(
            "Baseline report could not be saved."
          );
        }
      }

      /*
       * ========================================================
       * UPLOAD GENERATED EXCEL TO SUPABASE STORAGE
       * ========================================================
       */

      await handleBaselineStorageSync(
        farmerProjectId,
        farmerId,
        supabase
      );

      /*
       * ========================================================
       * SAVE / UPDATE PROJECT
       * ========================================================
       */

      const projectPayload = {
        project_id:
          farmerProjectId,

        farmer_id:
          farmerId,

        project_name:
          "Mangrove Restoration Project",

        location:
          "Blue Carbon Restoration Site",

        state:
          null,

        area_ha:
          areaHa,

        available_credits:
          totalCo2e,

        credit_price:
          1800,

        status:
          "PENDING_VERIFICATION",

        updated_at:
          new Date().toISOString(),
      };

      /*
       * First check whether the Farmer-specific project already exists.
       */

      const {
        data: existingFarmerProject,
        error: farmerProjectLookupError,
      } = await supabase
        .from("mangrove_projects")
        .select("id")
        .eq(
          "project_id",
          farmerProjectId
        )
        .eq(
          "farmer_id",
          farmerId
        )
        .maybeSingle();

      if (farmerProjectLookupError) {
        console.error(
          "Farmer project lookup error:",
          JSON.stringify(
            farmerProjectLookupError,
            null,
            2
          )
        );

        throw new Error(
          "Could not check the Farmer project."
        );
      }

      if (existingFarmerProject) {
        const {
          data: savedProject,
          error: projectUpdateError,
        } = await supabase
          .from("mangrove_projects")
          .update(
            projectPayload
          )
          .eq(
            "id",
            existingFarmerProject.id
          )
          .select()
          .single();

        if (projectUpdateError) {
          console.error(
            "Failed to update project:",
            JSON.stringify(
              projectUpdateError,
              null,
              2
            )
          );

          throw new Error(
            `Unable to update project for Authority verification: ${projectUpdateError.message}`
          );
        }

        console.log(
          "Project updated successfully:",
          savedProject
        );
      } else {
        const {
          data: savedProject,
          error: projectInsertError,
        } = await supabase
          .from("mangrove_projects")
          .insert(
            projectPayload
          )
          .select()
          .single();

        if (projectInsertError) {
          console.error(
            "Failed to create project:",
            JSON.stringify(
              projectInsertError,
              null,
              2
            )
          );

          throw new Error(
            `Unable to submit project for Authority verification: ${projectInsertError.message}`
          );
        }

        console.log(
          "Project created successfully:",
          savedProject
        );
      }

      /*
       * --------------------------------------------------------
       * SUCCESS
       * --------------------------------------------------------
       */

      setAnalysisMessage(
        `Baseline analysis complete. ${imagesProcessed} images processed and ${totalDetections} mangrove detections found. Your project has been submitted to the Authority for verification.`
      );
    } catch (error) {
      console.error(
        "AIML baseline analysis error:",
        error
      );

      setAnalysisMessage(
        error instanceof Error
          ? error.message
          : "Unable to connect to AIML baseline API. Make sure the Python API is running."
      );
    } finally {
      setIsAnalyzing(false);
    }
  };

  /*
   * ============================================================
   * MAIN PAGE
   * ============================================================
   */

  return (
    <div className="min-h-screen bg-sand-50 dark:bg-[#071a20]">

      <Navbar />

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">

        <button
          type="button"
          onClick={() =>
            router.push(
              "/farmer/dashboard"
            )
          }
          className="inline-flex items-center gap-2 mb-6 text-xs font-mono text-ink-soft dark:text-sand-100/60 hover:text-ink dark:hover:text-sand-50 transition-colors"
        >
          <ArrowLeft size={15} />

          <span>
            Back to Farmer Dashboard
          </span>
        </button>

        <motion.div
          initial={{
            opacity: 0,
            y: 12,
          }}
          animate={{
            opacity: 1,
            y: 0,
          }}
          transition={{
            duration: 0.45,
          }}
          className="rounded-[28px] border border-ocean-900/10 bg-white/80 dark:border-sand-100/10 dark:bg-[#0a232b]/80 backdrop-blur-md p-6 sm:p-8 shadow-soft mb-8"
        >

          <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6">

            <div className="space-y-3">

              <div className="flex items-center gap-2 text-[10px] font-mono uppercase tracking-wider text-mangrove-700 dark:text-mangrove-300">

                <Building2 size={14} />

                <span>
                  Blue Carbon Project
                </span>

              </div>

              <h1 className="font-display text-2xl sm:text-3xl font-semibold text-ink dark:text-sand-50 tracking-tight">
                Mangrove Restoration Project
              </h1>

              <div className="flex flex-wrap items-center gap-3 text-xs font-mono text-ink-soft dark:text-sand-100/60">

                <span className="inline-flex items-center gap-1.5">
                  <FileCheck2 size={13} />

                  Project ID:
                  {" "}

                  <span className="text-mangrove-700 dark:text-mangrove-300">
                    {projectId}
                  </span>
                </span>

                <span className="hidden sm:block">
                  •
                </span>

                <span className="inline-flex items-center gap-1.5">
                  <Layers size={13} />

                  Coastal Mangrove
                </span>

              </div>

            </div>

            <div className="flex items-center gap-3">

              <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-amber-500/10 border border-amber-500/20 text-amber-700 dark:text-amber-300 text-xs font-mono">

                <Clock size={13} />

                Under Review

              </div>

            </div>

          </div>

        </motion.div>

        <motion.div
          initial={{
            opacity: 0,
            y: 8,
          }}
          animate={{
            opacity: 1,
            y: 0,
          }}
          transition={{
            duration: 0.35,
          }}
          className="flex items-center gap-2 overflow-x-auto pb-2 mb-8"
        >

          {tabs.map((tab) => {

            const isActive =
              activeTab === tab.id;

            return (
              <button
                key={tab.id}
                type="button"
                onClick={() =>
                  setActiveTab(
                    tab.id as typeof activeTab
                  )
                }
                className={`relative px-4 py-2.5 rounded-xl text-xs font-mono tracking-wider transition-all whitespace-nowrap ${
                  isActive
                    ? "bg-ocean-900 text-sand-50 dark:bg-mangrove-500 dark:text-ink font-semibold shadow-sm"
                    : "text-ink-soft dark:text-sand-100/70 hover:text-ink dark:hover:text-sand-50 hover:bg-sand-100/50 dark:hover:bg-[#071a20]/50"
                }`}
              >
                {tab.label}
              </button>
            );
          })}

        </motion.div>

        {activeTab === "overview" && (
          <motion.div
            variants={containerVariants}
            initial="hidden"
            animate="visible"
            className="grid grid-cols-1 lg:grid-cols-12 gap-8"
          >

            <div className="lg:col-span-8 space-y-8">

              <motion.div
                variants={itemVariants}
                className="rounded-[28px] border border-ocean-900/10 bg-white/80 dark:border-sand-100/10 dark:bg-[#0a232b]/80 backdrop-blur-md p-6 sm:p-8 shadow-soft space-y-6"
              >

                <h2 className="font-display text-lg font-semibold text-ink dark:text-sand-50 tracking-tight border-b border-ocean-900/5 dark:border-sand-100/5 pb-4">
                  Plot Metadata & Field Telemetry
                </h2>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">

                  <div className="p-4 rounded-2xl bg-sand-50/70 dark:bg-[#071a20]/60 border border-ocean-900/5 dark:border-sand-100/5 flex items-start gap-3">

                    <MapPin
                      size={20}
                      className="text-mangrove-600 dark:text-mangrove-400 shrink-0 mt-0.5"
                    />

                    <div>

                      <span className="block text-[10px] font-mono uppercase tracking-wider text-ink-soft dark:text-sand-100/50">
                        GPS Coordinates
                      </span>

                      <span className="text-sm font-medium text-ink-faint dark:text-sand-100/40 block mt-1">
                        Awaiting Satellite Calibration
                      </span>

                    </div>

                  </div>

                  <div className="p-4 rounded-2xl bg-sand-50/70 dark:bg-[#071a20]/60 border border-ocean-900/5 dark:border-sand-100/5 flex items-start gap-3">

                    <Maximize2
                      size={20}
                      className="text-mangrove-600 dark:text-mangrove-400 shrink-0 mt-0.5"
                    />

                    <div>

                      <span className="block text-[10px] font-mono uppercase tracking-wider text-ink-soft dark:text-sand-100/50">
                        Total Area
                      </span>

                      <span className="text-sm font-medium text-ink-faint dark:text-sand-100/40 block mt-1 font-mono">
                        -- Hectares
                      </span>

                    </div>

                  </div>

                  <div className="p-4 rounded-2xl bg-sand-50/70 dark:bg-[#071a20]/60 border border-ocean-900/5 dark:border-sand-100/5 flex items-start gap-3">

                    <Calendar
                      size={20}
                      className="text-mangrove-600 dark:text-mangrove-400 shrink-0 mt-0.5"
                    />

                    <div>

                      <span className="block text-[10px] font-mono uppercase tracking-wider text-ink-soft dark:text-sand-100/50">
                        Registration Date
                      </span>

                      <span className="text-sm font-semibold text-ink dark:text-sand-50 block mt-1 font-mono">
                        Recently Submitted
                      </span>

                    </div>

                  </div>

                  <div className="p-4 rounded-2xl bg-sand-50/70 dark:bg-[#071a20]/60 border border-ocean-900/5 dark:border-sand-100/5 flex items-start gap-3">

                    <Layers
                      size={20}
                      className="text-mangrove-600 dark:text-mangrove-400 shrink-0 mt-0.5"
                    />

                    <div>

                      <span className="block text-[10px] font-mono uppercase tracking-wider text-ink-soft dark:text-sand-100/50">
                        Ecosystem Type
                      </span>

                      <span className="text-sm font-semibold text-ink dark:text-sand-50 block mt-1">
                        Coastal Mangrove
                      </span>

                    </div>

                  </div>

                </div>

              </motion.div>

              <motion.div
                variants={itemVariants}
                className="rounded-[28px] border border-ocean-900/10 bg-white/80 dark:border-sand-100/10 dark:bg-[#0a232b]/80 backdrop-blur-md p-6 sm:p-8 shadow-soft space-y-4"
              >

                <div className="flex items-center gap-3 border-b border-ocean-900/5 dark:border-sand-100/5 pb-4">

                  <Activity
                    size={20}
                    className="text-ocean-900 dark:text-sand-100"
                  />

                  <h2 className="font-display text-lg font-semibold text-ink dark:text-sand-50 tracking-tight">
                    MRV Telemetry & Satellite Data
                  </h2>

                </div>

                <div className="p-8 text-center rounded-2xl border border-dashed border-ocean-900/10 dark:border-sand-100/10 bg-sand-50/50 dark:bg-[#071a20]/50 space-y-2">

                  <Sparkles
                    size={24}
                    className="mx-auto text-mangrove-600 dark:text-mangrove-400"
                  />

                  <p className="text-sm font-medium text-ink dark:text-sand-50">
                    Telemetry Feed Initializing
                  </p>

                  <p className="text-xs text-ink-soft dark:text-sand-100/60 max-w-md mx-auto">
                    Remote sensing indices, biomass estimations, and drone imagery feeds will populate after site boundary verification.
                  </p>

                </div>

              </motion.div>

            </div>

            <div className="lg:col-span-4 space-y-8">

              <motion.div
                variants={itemVariants}
                className="rounded-[28px] border border-ocean-900/10 bg-white/80 dark:border-sand-100/10 dark:bg-[#0a232b]/80 backdrop-blur-md p-6 shadow-soft space-y-4"
              >

                <div className="flex items-center gap-2.5 pb-3 border-b border-ocean-900/5 dark:border-sand-100/5">

                  <ShieldCheck
                    size={20}
                    className="text-amber-600 dark:text-amber-400"
                  />

                  <h3 className="font-display text-base font-semibold text-ink dark:text-sand-50 tracking-tight">
                    Verification Status
                  </h3>

                </div>

                <p className="text-xs text-ink-soft dark:text-sand-100/70 leading-relaxed">
                  Your project application and land ownership proofs are currently under review by regional forest and carbon auditors.
                </p>

                <div className="p-3.5 rounded-xl bg-amber-500/10 border border-amber-500/20 text-xs font-mono text-amber-800 dark:text-amber-300">
                  Current Stage: Regional Audit
                </div>

              </motion.div>

              <motion.div
                variants={itemVariants}
                className="rounded-[28px] border border-ocean-900/10 bg-white/80 dark:border-sand-100/10 dark:bg-[#0a232b]/80 backdrop-blur-md p-6 shadow-soft space-y-4"
              >

                <div className="flex items-center gap-2.5 pb-3 border-b border-ocean-900/5 dark:border-sand-100/5">

                  <FileCheck2
                    size={20}
                    className="text-mangrove-600 dark:text-mangrove-400"
                  />

                  <h3 className="font-display text-base font-semibold text-ink dark:text-sand-50 tracking-tight">
                    Linked Documents
                  </h3>

                </div>

                <ul className="space-y-2 text-xs text-ink-soft dark:text-sand-100/80 font-mono">

                  <li className="flex items-center justify-between p-2.5 rounded-lg bg-sand-50/70 dark:bg-[#071a20]/60">

                    <span>
                      Land Title Deed
                    </span>

                    <span className="text-mangrove-700 dark:text-mangrove-300 font-bold">
                      ✓ Attached
                    </span>

                  </li>

                  <li className="flex items-center justify-between p-2.5 rounded-lg bg-sand-50/70 dark:bg-[#071a20]/60">

                    <span>
                      Farmer Identity Verification
                    </span>

                    <span className="text-mangrove-700 dark:text-mangrove-300 font-bold">
                      ✓ Verified
                    </span>

                  </li>

                </ul>

              </motion.div>

            </div>

          </motion.div>
        )}

        {activeTab === "baseline" && (
          <motion.div
            variants={containerVariants}
            initial="hidden"
            animate="visible"
            className="space-y-8"
          >

            <motion.div
              variants={itemVariants}
              className="rounded-[28px] border border-ocean-900/10 bg-white/80 dark:border-sand-100/10 dark:bg-[#0a232b]/80 backdrop-blur-md p-6 sm:p-8 shadow-soft"
            >

              <div className="flex items-center gap-2.5 pb-3 border-b border-ocean-900/5 dark:border-sand-100/5">

                <Trees
                  size={20}
                  className="text-mangrove-600 dark:text-mangrove-400"
                />

                <h3 className="font-display text-base font-semibold text-ink dark:text-sand-50 tracking-tight">
                  AI Mangrove Baseline Analysis
                </h3>

              </div>

              <div className="mt-5 space-y-4">

                <p className="text-xs text-ink-soft dark:text-sand-100/60">
                  Upload the mangrove image ZIP. The BlueCarbon Nexus YOLO model will process all images and generate one aggregated baseline report.
                </p>

                <input
                  type="file"
                  accept=".zip,application/zip"
                  onChange={(event) => {

                    const file =
                      event.target.files?.[0] ||
                      null;

                    setSelectedFile(file);

                    setAnalysisMessage("");

                    setAnalysisResult(null);

                    setAnalysisDate(null);

                    event.target.value = "";

                  }}
                  className="block w-full text-sm text-ink-soft dark:text-sand-100/60 file:mr-4 file:rounded-xl file:border-0 file:px-4 file:py-2 file:bg-mangrove-500/10 file:text-mangrove-700 dark:file:text-mangrove-300 file:font-medium"
                />

                {selectedFile && (
                  <p className="text-xs font-mono text-ink-soft dark:text-sand-100/60">
                    Selected ZIP:{" "}
                    {selectedFile.name}
                  </p>
                )}

                <button
                  type="button"
                  onClick={analyzeBaseline}
                  disabled={
                    !selectedFile ||
                    isAnalyzing
                  }
                  className="inline-flex items-center gap-2 rounded-xl px-5 py-3 bg-mangrove-600 text-white text-xs font-mono font-medium hover:bg-mangrove-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                >

                  <Sparkles size={15} />

                  {isAnalyzing
                    ? "Analyzing Baseline..."
                    : analysisResult
                      ? "Run Analysis Again"
                      : "Generate AI Baseline"}

                </button>

                {isAnalyzing && (
                  <div className="rounded-xl border border-ocean-900/10 bg-sand-50/70 dark:bg-[#071a20]/60 p-4 text-xs font-mono text-ink-soft dark:text-sand-100/70">

                    <div className="flex items-center gap-2">

                      <Activity
                        size={14}
                        className="animate-pulse text-mangrove-600"
                      />

                      <span>
                        YOLO analysis is running. Processing all images and generating the baseline carbon report...
                      </span>

                    </div>

                  </div>
                )}

                {analysisMessage &&
                  !isAnalyzing && (
                    <div className="rounded-xl bg-sand-50/70 dark:bg-[#071a20]/60 p-4 text-xs font-mono text-ink-soft dark:text-sand-100/70">
                      {analysisMessage}
                    </div>
                  )}

                {analysisResult && (
                  <div className="space-y-4">

                    <div className="flex items-center gap-2 text-xs font-mono text-mangrove-700 dark:text-mangrove-300">

                      <CheckCircle2 size={15} />

                      <span>
                        AI baseline analysis completed successfully.
                      </span>

                    </div>

                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">

                      <div className="p-4 rounded-xl bg-mangrove-500/10 border border-mangrove-500/20">

                        <span className="block text-[10px] uppercase tracking-wider text-ink-soft dark:text-sand-100/50">
                          Images Processed
                        </span>

                        <span className="block mt-1 text-2xl font-mono font-semibold text-ink dark:text-sand-50">

                          {Number(
                            analysisResult.images_processed ??
                              0
                          ).toLocaleString()}

                        </span>

                      </div>

                      <div className="p-4 rounded-xl bg-sand-50/70 dark:bg-[#071a20]/60 border border-ocean-900/5 dark:border-sand-100/5">

                        <span className="block text-[10px] uppercase tracking-wider text-ink-soft dark:text-sand-100/50">
                          Mangrove Detections
                        </span>

                        <span className="block mt-1 text-2xl font-mono font-semibold text-ink dark:text-sand-50">

                          {Number(
                            analysisResult.total_detections ??
                              0
                          ).toLocaleString()}

                        </span>

                      </div>

                      <div className="p-4 rounded-xl bg-sand-50/70 dark:bg-[#071a20]/60 border border-ocean-900/5 dark:border-sand-100/5">

                        <span className="block text-[10px] uppercase tracking-wider text-ink-soft dark:text-sand-100/50">
                          Detected Area
                        </span>

                        <span className="block mt-1 text-sm font-medium text-ink dark:text-sand-50">

                          {Number(
                            analysisResult.total_area_hectares ??
                              analysisResult.area_ha ??
                              0
                          ).toFixed(6)}{" "}
                          ha

                        </span>

                      </div>

                      <div className="p-4 rounded-xl bg-sand-50/70 dark:bg-[#071a20]/60 border border-ocean-900/5 dark:border-sand-100/5">

                        <span className="block text-[10px] uppercase tracking-wider text-ink-soft dark:text-sand-100/50">
                          CO₂ Equivalent
                        </span>

                        <span className="block mt-1 text-sm font-medium text-mangrove-700 dark:text-mangrove-300">

                          {Number(
                            analysisResult.total_co2e ??
                              analysisResult.total_co2_tons ??
                              0
                          ).toFixed(4)}{" "}
                          tCO₂e

                        </span>

                      </div>

                    </div>

                  </div>
                )}

                <div className="rounded-xl border border-amber-500/20 bg-amber-500/10 p-4 text-[11px] leading-relaxed text-amber-800 dark:text-amber-300">

                  The ZIP is processed as one baseline dataset. All supported images inside the ZIP, including nested ZIP files, are processed by the Python YOLO API and the results are aggregated into one baseline report.

                </div>

              </div>

            </motion.div>

            {analysisResult && (
              <motion.div
                variants={itemVariants}
                className="space-y-8"
              >

                <div className="flex items-center justify-between flex-wrap gap-4 p-4 rounded-2xl bg-emerald-500/10 border border-emerald-500/20">

                  <div className="flex items-center gap-2 text-xs text-emerald-800 dark:text-emerald-300">

                    <CheckCircle2
                      size={16}
                      className="shrink-0"
                    />

                    <span>

                      <strong>
                        Baseline Report Generated:
                      </strong>{" "}
                      The AI analysis has completed and the aggregated Excel report is ready.

                    </span>

                  </div>

                  <button
                    type="button"
                    onClick={() => {
                      window.location.href =
                        "/api/aiml/report";
                    }}
                    className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-ocean-900 text-sand-50 dark:bg-mangrove-500 dark:text-ink font-mono text-[11px] font-semibold uppercase tracking-wider hover:opacity-90 transition-opacity"
                  >

                    <Download size={13} />

                    <span>
                      Download Baseline Report (Excel)
                    </span>

                  </button>

                </div>

                <motion.div
                  variants={containerVariants}
                  className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4"
                >

                  <motion.div
                    variants={itemVariants}
                    className="p-5 rounded-2xl bg-white/80 dark:bg-[#0a232b]/80 border border-ocean-900/10 dark:border-sand-100/10 shadow-soft"
                  >

                    <span className="block text-[10px] font-mono uppercase tracking-wider text-ink-soft dark:text-sand-100/50">
                      Baseline Carbon Stock
                    </span>

                    <span className="text-2xl font-display font-semibold text-ink dark:text-sand-50 block mt-1 font-mono">

                      {Number(
                        analysisResult.total_co2e ??
                          analysisResult.total_co2_tons ??
                          0
                      ).toLocaleString(
                        undefined,
                        {
                          minimumFractionDigits: 4,
                          maximumFractionDigits: 4,
                        }
                      )}

                      <span className="text-xs text-ink-soft font-normal ml-1">
                        tCO₂e
                      </span>

                    </span>

                    <span className="inline-block mt-2 px-2 py-0.5 rounded text-[10px] font-mono bg-emerald-500/10 text-emerald-700 dark:text-emerald-300 border border-emerald-500/20">
                      AI Generated
                    </span>

                  </motion.div>

                  <motion.div
                    variants={itemVariants}
                    className="p-5 rounded-2xl bg-white/80 dark:bg-[#0a232b]/80 border border-ocean-900/10 dark:border-sand-100/10 shadow-soft"
                  >

                    <span className="block text-[10px] font-mono uppercase tracking-wider text-ink-soft dark:text-sand-100/50">
                      Baseline Date
                    </span>

                    <span className="text-xl font-display font-semibold text-ink dark:text-sand-50 block mt-1">

                      {analysisDate
                        ? new Date(
                            analysisDate
                          ).toLocaleDateString(
                            "en-IN",
                            {
                              day: "2-digit",
                              month: "short",
                              year: "numeric",
                            }
                          )
                        : "Not available"}

                    </span>

                    <span className="block text-[10px] font-mono text-ink-soft dark:text-sand-100/60 mt-2">
                      Date of AI analysis
                    </span>

                  </motion.div>

                  <motion.div
                    variants={itemVariants}
                    className="p-5 rounded-2xl bg-white/80 dark:bg-[#0a232b]/80 border border-ocean-900/10 dark:border-sand-100/10 shadow-soft"
                  >

                    <span className="block text-[10px] font-mono uppercase tracking-wider text-ink-soft dark:text-sand-100/50">
                      Verification Status
                    </span>

                    <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-mono font-medium bg-amber-500/10 text-amber-700 dark:bg-amber-500/20 dark:text-amber-300 border border-amber-500/20 mt-2">

                      <span className="h-1.5 w-1.5 rounded-full bg-amber-500 animate-pulse" />

                      <span>
                        Pending Verification
                      </span>

                    </div>

                  </motion.div>

                  <motion.div
                    variants={itemVariants}
                    className="p-5 rounded-2xl bg-white/80 dark:bg-[#0a232b]/80 border border-ocean-900/10 dark:border-sand-100/10 shadow-soft"
                  >

                    <span className="block text-[10px] font-mono uppercase tracking-wider text-ink-soft dark:text-sand-100/50">
                      Methodology
                    </span>

                    <span className="text-sm font-semibold text-ink dark:text-sand-50 block mt-1">
                      BlueCarbon Nexus Assessment
                    </span>

                    <span className="block text-[10px] font-mono text-ink-soft dark:text-sand-100/60 mt-2">
                      YOLOv8 + IPCC-based carbon estimation
                    </span>

                  </motion.div>

                </motion.div>

                <motion.div
                  variants={itemVariants}
                  className="rounded-[28px] border border-ocean-900/10 bg-white/80 dark:border-sand-100/10 dark:bg-[#0a232b]/80 backdrop-blur-md p-6 sm:p-8 shadow-soft"
                >

                  <div className="flex items-center gap-2.5 pb-3 border-b border-ocean-900/5 dark:border-sand-100/5">

                    <BarChart3
                      size={20}
                      className="text-mangrove-600 dark:text-mangrove-400"
                    />

                    <h3 className="font-display text-base font-semibold text-ink dark:text-sand-50 tracking-tight">
                      Baseline Carbon Results
                    </h3>

                  </div>

                  <div className="mt-5 space-y-3 text-xs">

                    <div className="flex items-center justify-between p-3 rounded-xl bg-sand-50/70 dark:bg-[#071a20]/60">

                      <span className="text-ink-soft dark:text-sand-100/70">
                        Above-ground carbon
                      </span>

                      <span className="font-mono font-semibold text-ink dark:text-sand-50">

                        {Number(
                          analysisResult.total_agb_tC ??
                            analysisResult.agb_tC ??
                            0
                        ).toLocaleString(
                          undefined,
                          {
                            minimumFractionDigits: 4,
                            maximumFractionDigits: 4,
                          }
                        )}{" "}
                        tC

                      </span>

                    </div>

                    <div className="flex items-center justify-between p-3 rounded-xl bg-sand-50/70 dark:bg-[#071a20]/60">

                      <span className="text-ink-soft dark:text-sand-100/70">
                        Below-ground carbon
                      </span>

                      <span className="font-mono font-semibold text-ink dark:text-sand-50">

                        {Number(
                          analysisResult.total_bgb_tC ??
                            analysisResult.bgb_tC ??
                            0
                        ).toLocaleString(
                          undefined,
                          {
                            minimumFractionDigits: 4,
                            maximumFractionDigits: 4,
                          }
                        )}{" "}
                        tC

                      </span>

                    </div>

                    <div className="flex items-center justify-between p-3 rounded-xl bg-sand-50/70 dark:bg-[#071a20]/60">

                      <span className="text-ink-soft dark:text-sand-100/70">
                        Soil organic carbon
                      </span>

                      <span className="font-mono font-semibold text-ink dark:text-sand-50">

                        {Number(
                          analysisResult.total_soc_tC ??
                            analysisResult.soc_tC ??
                            0
                        ).toLocaleString(
                          undefined,
                          {
                            minimumFractionDigits: 4,
                            maximumFractionDigits: 4,
                          }
                        )}{" "}
                        tC

                      </span>

                    </div>

                    <div className="flex items-center justify-between p-3 rounded-xl bg-mangrove-500/15 border border-mangrove-500/20 text-mangrove-900 dark:text-mangrove-200">

                      <span className="font-semibold">
                        Total Carbon
                      </span>

                      <span className="font-mono font-bold text-sm">

                        {Number(
                          analysisResult.total_carbon_tC ??
                            analysisResult.total_carbon ??
                            0
                        ).toLocaleString(
                          undefined,
                          {
                            minimumFractionDigits: 4,
                            maximumFractionDigits: 4,
                          }
                        )}{" "}
                        tC

                      </span>

                    </div>

                    <div className="flex items-center justify-between p-3.5 rounded-xl bg-ocean-900/10 border border-ocean-900/20">

                      <span className="font-semibold text-ink dark:text-sand-50">
                        CO₂ Equivalent
                      </span>

                      <span className="font-mono font-bold text-sm text-mangrove-700 dark:text-mangrove-300">

                        {Number(
                          analysisResult.total_co2e ??
                            analysisResult.total_co2_tons ??
                            0
                        ).toLocaleString(
                          undefined,
                          {
                            minimumFractionDigits: 4,
                            maximumFractionDigits: 4,
                          }
                        )}{" "}
                        tCO₂e

                      </span>

                    </div>

                  </div>

                </motion.div>

              </motion.div>
            )}

          </motion.div>
        )}

        {activeTab === "mrv" && (
          <motion.div
            variants={containerVariants}
            initial="hidden"
            animate="visible"
            className="space-y-8"
          >

            <motion.div
              variants={itemVariants}
              className="rounded-[28px] border border-ocean-900/10 bg-white/80 dark:border-sand-100/10 dark:bg-[#0a232b]/80 backdrop-blur-md p-6 sm:p-8 shadow-soft flex flex-col md:flex-row items-start md:items-center justify-between gap-6"
            >

              <div className="space-y-2">

                <div className="flex items-center gap-3">

                  <Activity
                    size={22}
                    className="text-mangrove-600 dark:text-mangrove-400"
                  />

                  <h2 className="font-display text-xl font-semibold text-ink dark:text-sand-50 tracking-tight">
                    MRV & Verification
                  </h2>

                  <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-mono font-medium bg-emerald-500/10 text-emerald-700 dark:bg-emerald-500/20 dark:text-emerald-300 border border-emerald-500/20">

                    <span className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse" />

                    <span>
                      🟢 Monitoring Active
                    </span>

                  </span>

                </div>

                <p className="text-xs text-ink-soft dark:text-sand-100/60">
                  Continuous environmental monitoring and verification status for site telemetry.
                </p>

              </div>

              <div className="flex items-center gap-6 text-xs font-mono border-t md:border-t-0 md:border-l border-ocean-900/5 dark:border-sand-100/5 pt-4 md:pt-0 md:pl-6">

                <div>

                  <span className="block text-[10px] uppercase text-ink-soft dark:text-sand-100/50">
                    Last Monitoring
                  </span>

                  <span className="font-medium text-ink dark:text-sand-50">
                    15 Aug 2026
                  </span>

                </div>

                <div>

                  <span className="block text-[10px] uppercase text-ink-soft dark:text-sand-100/50">
                    Next Monitoring
                  </span>

                  <span className="font-medium text-mangrove-700 dark:text-mangrove-300">
                    15 Nov 2026
                  </span>

                </div>

              </div>

            </motion.div>

            <div className="space-y-4">

              <h3 className="font-display text-base font-semibold text-ink dark:text-sand-50 tracking-tight">
                Data Sources
              </h3>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">

                {[
                  {
                    icon: "🚁",
                    title: "Drone Survey",
                    text: "High-resolution canopy photography and site orthomosaics.",
                    status: "Available",
                  },
                  {
                    icon: "satellite",
                    title: "Satellite Data",
                    text: "Multispectral canopy density and area observations.",
                    status: "Available",
                  },
                  {
                    icon: "trees",
                    title: "Field Survey",
                    text: "On-ground plot measurements, species verification, and soil samples.",
                    status: "Completed",
                  },
                ].map(
                  (item) => (
                    <motion.div
                      key={item.title}
                      variants={itemVariants}
                      className="p-5 rounded-2xl bg-white/80 dark:bg-[#0a232b]/80 border border-ocean-900/10 dark:border-sand-100/10 shadow-soft space-y-4 flex flex-col justify-between"
                    >

                      <div className="space-y-2">

                        <div className="flex items-center justify-between">

                          {item.icon ===
                          "satellite" ? (
                            <Satellite
                              size={24}
                              className="text-ocean-900 dark:text-sand-100"
                            />
                          ) : item.icon ===
                            "trees" ? (
                            <Trees
                              size={24}
                              className="text-mangrove-600 dark:text-mangrove-400"
                            />
                          ) : (
                            <span className="text-2xl">
                              {item.icon}
                            </span>
                          )}

                          <span className="px-2 py-0.5 rounded text-[10px] font-mono bg-emerald-500/10 text-emerald-700 dark:text-emerald-300 border border-emerald-500/20 font-medium">
                            {item.status}
                          </span>

                        </div>

                        <h4 className="font-display text-sm font-semibold text-ink dark:text-sand-50">
                          {item.title}
                        </h4>

                        <p className="text-xs text-ink-soft dark:text-sand-100/60">
                          {item.text}
                        </p>

                      </div>

                      <button
                        type="button"
                        onClick={() =>
                          alert(
                            `Viewing Demo ${item.title} Evidence...`
                          )
                        }
                        className="inline-flex items-center gap-1.5 w-full justify-center px-3 py-2 rounded-xl bg-sand-50 dark:bg-[#071a20] border border-ocean-900/10 dark:border-sand-100/10 text-ink dark:text-sand-100 text-xs font-mono hover:bg-sand-100 dark:hover:bg-[#0a232b] transition-colors"
                      >

                        <Eye size={13} />

                        <span>
                          View Evidence (Demo)
                        </span>

                      </button>

                    </motion.div>
                  )
                )}

              </div>

            </div>

            <div className="space-y-4">

              <div className="flex items-center justify-between">

                <h3 className="font-display text-base font-semibold text-ink dark:text-sand-50 tracking-tight">
                  Latest Monitoring Results
                </h3>

                <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-mangrove-500/10 text-mangrove-700 dark:text-mangrove-300 border border-mangrove-500/20">
                  Demo / Sample Data
                </span>

              </div>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">

                <motion.div
                  variants={itemVariants}
                  className="p-5 rounded-2xl bg-white/80 dark:bg-[#0a232b]/80 border border-ocean-900/10 dark:border-sand-100/10 shadow-soft"
                >

                  <span className="block text-[10px] font-mono uppercase tracking-wider text-ink-soft dark:text-sand-100/50">
                    Mangrove Area
                  </span>

                  <span className="text-2xl font-display font-semibold text-ink dark:text-sand-50 block mt-1 font-mono">
                    10.2{" "}
                    <span className="text-xs text-ink-soft font-normal">
                      ha
                    </span>
                  </span>

                </motion.div>

                <motion.div
                  variants={itemVariants}
                  className="p-5 rounded-2xl bg-white/80 dark:bg-[#0a232b]/80 border border-ocean-900/10 dark:border-sand-100/10 shadow-soft"
                >

                  <span className="block text-[10px] font-mono uppercase tracking-wider text-ink-soft dark:text-sand-100/50">
                    Biomass Estimate
                  </span>

                  <span className="text-2xl font-display font-semibold text-ink dark:text-sand-50 block mt-1 font-mono">
                    1,350{" "}
                    <span className="text-xs text-ink-soft font-normal">
                      tonnes
                    </span>
                  </span>

                </motion.div>

                <motion.div
                  variants={itemVariants}
                  className="p-5 rounded-2xl bg-white/80 dark:bg-[#0a232b]/80 border border-ocean-900/10 dark:border-sand-100/10 shadow-soft"
                >

                  <span className="block text-[10px] font-mono uppercase tracking-wider text-ink-soft dark:text-sand-100/50">
                    Carbon Stock
                  </span>

                  <span className="text-2xl font-display font-semibold text-mangrove-700 dark:text-mangrove-300 block mt-1 font-mono">
                    1,420{" "}
                    <span className="text-xs text-ink-soft font-normal">
                      tCO₂e
                    </span>
                  </span>

                </motion.div>

              </div>

            </div>

            <motion.div
              variants={itemVariants}
              className="rounded-[28px] border border-ocean-900/10 bg-white/80 dark:border-sand-100/10 dark:bg-[#0a232b]/80 backdrop-blur-md p-6 sm:p-8 shadow-soft space-y-6"
            >

              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-ocean-900/5 dark:border-sand-100/5 pb-4">

                <div className="flex items-center gap-2.5">

                  <ShieldCheck
                    size={20}
                    className="text-amber-600 dark:text-amber-400"
                  />

                  <h3 className="font-display text-base font-semibold text-ink dark:text-sand-50 tracking-tight">
                    Verification
                  </h3>

                </div>

                <div className="flex items-center gap-3">

                  <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-mono font-medium bg-amber-500/10 text-amber-700 dark:bg-amber-500/20 dark:text-amber-300 border border-amber-500/20">

                    <span className="h-1.5 w-1.5 rounded-full bg-amber-500 animate-pulse" />

                    <span>
                      🟡 Under Review
                    </span>

                  </span>

                  <span className="text-xs font-mono text-ink-soft dark:text-sand-100/50">
                    Last Updated: 15 Sep 2026
                  </span>

                </div>

              </div>

              <div className="p-4 rounded-xl bg-sand-50/70 dark:bg-[#071a20]/60 border border-ocean-900/5 dark:border-sand-100/5 text-xs text-ink-soft dark:text-sand-100/70 leading-relaxed">
                Your monitoring data is being reviewed as part of the project verification process.
              </div>

              <div className="space-y-3 pt-2">

                <span className="block text-[10px] font-mono uppercase tracking-wider text-ink-soft dark:text-sand-100/50">
                  Verification Roadmap
                </span>

                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs font-mono">

                  <div className="p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-800 dark:text-emerald-300 flex items-center gap-2">

                    <Check size={14} />

                    <div>

                      <span className="block text-[9px] opacity-70">
                        Step 1
                      </span>

                      <span className="font-medium">
                        Data Collection
                      </span>

                    </div>

                  </div>

                  <div className="p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-800 dark:text-emerald-300 flex items-center gap-2">

                    <Check size={14} />

                    <div>

                      <span className="block text-[9px] opacity-70">
                        Step 2
                      </span>

                      <span className="font-medium">
                        MRV Review
                      </span>

                    </div>

                  </div>

                  <div className="p-3 rounded-xl bg-amber-500/15 border border-amber-500/30 text-amber-800 dark:text-amber-300 flex items-center gap-2 ring-1 ring-amber-500/30">

                    <Clock
                      size={14}
                      className="shrink-0"
                    />

                    <div>

                      <span className="block text-[9px] opacity-70">
                        Step 3 (Active)
                      </span>

                      <span className="font-bold">
                        Regional Audit
                      </span>

                    </div>

                  </div>

                  <div className="p-3 rounded-xl bg-sand-50/50 dark:bg-[#071a20]/40 border border-ocean-900/5 dark:border-sand-100/5 text-ink-faint dark:text-sand-100/40 flex items-center gap-2">

                    <div className="h-3.5 w-3.5 rounded-full border border-current shrink-0" />

                    <div>

                      <span className="block text-[9px] opacity-70">
                        Step 4
                      </span>

                      <span className="font-medium">
                        Verified
                      </span>

                    </div>

                  </div>

                </div>

              </div>

            </motion.div>

          </motion.div>
        )}

        {activeTab === "credits" && (
          <motion.div
            variants={containerVariants}
            initial="hidden"
            animate="visible"
            className="space-y-8"
          >

            <motion.div
              variants={itemVariants}
              className="rounded-[28px] border border-ocean-900/10 bg-white/80 dark:border-sand-100/10 dark:bg-[#0a232b]/80 backdrop-blur-md p-6 sm:p-8 shadow-soft space-y-6"
            >

              <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6 border-b border-ocean-900/5 dark:border-sand-100/5 pb-6">

                <div className="space-y-2">

                  <div className="flex items-center gap-3">

                    <Coins
                      size={24}
                      className="text-amber-600 dark:text-amber-400"
                    />

                    <h2 className="font-display text-xl font-semibold text-ink dark:text-sand-50 tracking-tight">
                      Carbon Credits
                    </h2>

                    <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-mono font-medium bg-amber-500/10 text-amber-700 dark:bg-amber-500/20 dark:text-amber-300 border border-amber-500/20">

                      <span className="h-1.5 w-1.5 rounded-full bg-amber-500 animate-pulse" />

                      <span>
                        🟡 Not Yet Issued
                      </span>

                    </span>

                  </div>

                  <p className="text-xs text-ink-soft dark:text-sand-100/60 max-w-xl">
                    Carbon credits will be issued after the project completes the required monitoring and verification process.
                  </p>

                </div>

                <div className="flex items-center gap-4 w-full md:w-auto">

                  <button
                    type="button"
                    onClick={() =>
                      router.push(
                        "/industry/marketplace"
                      )
                    }
                    className="inline-flex items-center justify-center gap-2 px-5 py-3 rounded-2xl bg-ocean-900 text-sand-50 dark:bg-mangrove-500 dark:text-ink font-mono text-xs font-semibold uppercase tracking-wider hover:opacity-90 transition-opacity shadow-sm w-full md:w-auto"
                  >

                    <Store size={15} />

                    <span>
                      View Marketplace
                    </span>

                  </button>

                </div>

              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">

                <div className="p-5 rounded-2xl bg-sand-50/70 dark:bg-[#071a20]/60 border border-ocean-900/5 dark:border-sand-100/5 flex items-center justify-between">

                  <div>

                    <span className="block text-[10px] font-mono uppercase tracking-wider text-ink-soft dark:text-sand-100/50">
                      Available Credits
                    </span>

                    <span className="text-3xl font-display font-semibold text-ink dark:text-sand-50 block mt-1 font-mono">
                      0
                    </span>

                  </div>

                  <Lock
                    size={20}
                    className="text-ink-faint dark:text-sand-100/30"
                  />

                </div>

                <div className="p-5 rounded-2xl bg-sand-50/70 dark:bg-[#071a20]/60 border border-ocean-900/5 dark:border-sand-100/5 flex items-center justify-between">

                  <div>

                    <span className="block text-[10px] font-mono uppercase tracking-wider text-ink-soft dark:text-sand-100/50">
                      Issued Credits
                    </span>

                    <span className="text-3xl font-display font-semibold text-ink dark:text-sand-50 block mt-1 font-mono">
                      0
                    </span>

                  </div>

                  <Lock
                    size={20}
                    className="text-ink-faint dark:text-sand-100/30"
                  />

                </div>

              </div>

            </motion.div>

            <motion.div
              variants={itemVariants}
              className="rounded-[28px] border border-ocean-900/10 bg-white/80 dark:border-sand-100/10 dark:bg-[#0a232b]/80 backdrop-blur-md p-6 sm:p-8 shadow-soft space-y-4"
            >

              <h3 className="font-display text-base font-semibold text-ink dark:text-sand-50 tracking-tight">
                Credit Issuance Journey
              </h3>

              <div className="grid grid-cols-1 sm:grid-cols-4 gap-3 text-xs font-mono pt-2">

                <div className="p-4 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-800 dark:text-emerald-300 flex items-center justify-between">

                  <div className="flex items-center gap-2">

                    <Check size={16} />

                    <div>

                      <span className="block text-[9px] opacity-70">
                        Step 1
                      </span>

                      <span className="font-semibold">
                        MRV Monitoring
                      </span>

                    </div>

                  </div>

                  <ArrowRight
                    size={14}
                    className="hidden sm:block opacity-40"
                  />

                </div>

                <div className="p-4 rounded-2xl bg-amber-500/15 border border-amber-500/30 text-amber-800 dark:text-amber-300 flex items-center justify-between ring-1 ring-amber-500/30">

                  <div className="flex items-center gap-2">

                    <Clock
                      size={16}
                      className="shrink-0"
                    />

                    <div>

                      <span className="block text-[9px] opacity-70">
                        Step 2 (Active)
                      </span>

                      <span className="font-bold">
                        Verification
                      </span>

                    </div>

                  </div>

                  <ArrowRight
                    size={14}
                    className="hidden sm:block opacity-40"
                  />

                </div>

                <div className="p-4 rounded-2xl bg-sand-50/50 dark:bg-[#071a20]/40 border border-ocean-900/5 dark:border-sand-100/5 text-ink-faint dark:text-sand-100/40 flex items-center justify-between">

                  <div className="flex items-center gap-2">

                    <Lock
                      size={15}
                      className="shrink-0 opacity-60"
                    />

                    <div>

                      <span className="block text-[9px] opacity-70">
                        Step 3
                      </span>

                      <span className="font-medium">
                        Credit Issuance
                      </span>

                    </div>

                  </div>

                  <ArrowRight
                    size={14}
                    className="hidden sm:block opacity-40"
                  />

                </div>

                <div className="p-4 rounded-2xl bg-sand-50/50 dark:bg-[#071a20]/40 border border-ocean-900/5 dark:border-sand-100/5 text-ink-faint dark:text-sand-100/40 flex items-center gap-2">

                  <Lock
                    size={15}
                    className="shrink-0 opacity-60"
                  />

                  <div>

                    <span className="block text-[9px] opacity-70">
                      Step 4
                    </span>

                    <span className="font-medium">
                      Marketplace
                    </span>

                  </div>

                </div>

              </div>

            </motion.div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">

              <motion.div
                variants={itemVariants}
                className="lg:col-span-7 rounded-[28px] border border-ocean-900/10 bg-white/80 dark:border-sand-100/10 dark:bg-[#0a232b]/80 backdrop-blur-md p-6 sm:p-8 shadow-soft space-y-4"
              >

                <div className="flex items-center gap-2.5 pb-3 border-b border-ocean-900/5 dark:border-sand-100/5">

                  <Building2
                    size={20}
                    className="text-mangrove-600 dark:text-mangrove-400"
                  />

                  <h3 className="font-display text-base font-semibold text-ink dark:text-sand-50 tracking-tight">
                    Credit Details
                  </h3>

                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs font-mono">

                  <div className="p-3 rounded-xl bg-sand-50/70 dark:bg-[#071a20]/60">

                    <span className="block text-[10px] uppercase text-ink-soft dark:text-sand-100/50">
                      Project
                    </span>

                    <span className="font-sans font-medium text-ink dark:text-sand-50 block mt-0.5">
                      Mangrove Restoration Project
                    </span>

                  </div>

                  <div className="p-3 rounded-xl bg-sand-50/70 dark:bg-[#071a20]/60">

                    <span className="block text-[10px] uppercase text-ink-soft dark:text-sand-100/50">
                      Project ID
                    </span>

                    <span className="font-medium text-mangrove-700 dark:text-mangrove-300 block mt-0.5">
                      {projectId}
                    </span>

                  </div>

                  <div className="p-3 rounded-xl bg-sand-50/70 dark:bg-[#071a20]/60">

                    <span className="block text-[10px] uppercase text-ink-soft dark:text-sand-100/50">
                      Ecosystem
                    </span>

                    <span className="font-sans font-medium text-ink dark:text-sand-50 block mt-0.5">
                      Coastal Mangrove
                    </span>

                  </div>

                  <div className="p-3 rounded-xl bg-sand-50/70 dark:bg-[#071a20]/60">

                    <span className="block text-[10px] uppercase text-ink-soft dark:text-sand-100/50">
                      Verification Status
                    </span>

                    <span className="font-medium text-amber-700 dark:text-amber-300 block mt-0.5">
                      Pending Verification
                    </span>

                  </div>

                  <div className="p-3 rounded-xl bg-sand-50/70 dark:bg-[#071a20]/60">

                    <span className="block text-[10px] uppercase text-ink-soft dark:text-sand-100/50">
                      Credits Issued
                    </span>

                    <span className="font-bold text-ink dark:text-sand-50 block mt-0.5">
                      0
                    </span>

                  </div>

                  <div className="p-3 rounded-xl bg-sand-50/70 dark:bg-[#071a20]/60">

                    <span className="block text-[10px] uppercase text-ink-soft dark:text-sand-100/50">
                      Credit Type
                    </span>

                    <span className="font-sans font-medium text-ink dark:text-sand-50 block mt-0.5">
                      Carbon Credits
                    </span>

                  </div>

                </div>

              </motion.div>

              <motion.div
                variants={itemVariants}
                className="lg:col-span-5 rounded-[28px] border border-ocean-900/10 bg-white/80 dark:border-sand-100/10 dark:bg-[#0a232b]/80 backdrop-blur-md p-6 sm:p-8 shadow-soft space-y-4"
              >

                <div className="flex items-center gap-2.5 pb-3 border-b border-ocean-900/5 dark:border-sand-100/5">

                  <Info
                    size={20}
                    className="text-ocean-900 dark:text-sand-100"
                  />

                  <h3 className="font-display text-base font-semibold text-ink dark:text-sand-50 tracking-tight">
                    What happens next?
                  </h3>

                </div>

                <p className="text-xs text-ink-soft dark:text-sand-100/70 leading-relaxed">
                  Once MRV data is reviewed and the project is verified, eligible carbon credits can be recorded and made available for the marketplace.
                </p>

                <div className="p-4 rounded-xl bg-sand-50/70 dark:bg-[#071a20]/60 border border-ocean-900/5 dark:border-sand-100/5 text-xs text-ink-soft dark:text-sand-100/60 italic leading-relaxed">

                  &quot;You will receive a notification as soon as regional auditors finalize the site verification assessment.&quot;

                </div>

              </motion.div>

            </div>

          </motion.div>
        )}

      </main>

      <Footer />

    </div>
  );
}